app_booking/urls.py
from django.urls import path
from . import views

app_name = 'app_booking'  

urlpatterns = [
    path('rooms/', views.room_list, name='room_list'),
    path('book/<int:room_id>', views.book_room, name='book_room'),
    path('list/', views.booking_list, name='booking_list'),

    path('dashboard/', views.booking_dashboard, name='booking_dashboard'),
    path('approve/', views.approve_booking, name='approve_booking'),
    path('reject/', views.reject_booking, name='reject_booking'),

    path('admin/rooms/', views.admin_room_list, name='admin_room_list'),
    path('admin/rooms/add/', views.add_room, name='add_room'),
    path('admin/rooms/<int:room_id>/edit/', views.edit_room, name='edit_room'),
    path('admin/rooms/<int:room_id>/delete/', views.delete_room, name='delete_room'),
]

app_general/urls.py
from django.urls import include, path

from app_general import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("change-theme", views.change_theme, name="change_theme"),
]


handler500 = views.server_error
handler404 = views.page_not_found
handler403 = views.permission_denied

app_users/urls.py
from django.urls import include, path

from app_users import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register", views.register, name="register"),
    path("register/thankyou", views.register_thankyou, name="register_thankyou"),
    path("activate/<str:uidb64>/<str:token>", views.activate, name="activate"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("profile", views.profile, name="profile"),
    path('list', views.user_list, name='user_list'),
    path('edit', views.edit_user, name='edit_user'),  
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('delete', views.delete_user, name='delete_user')
]

room_booking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("app_general.urls")),
    path("users/", include("app_users.urls")),
    path("booking/", include("app_booking.urls")),
    path('admin/', admin.site.urls),
]

app_general/views.py
from datetime import datetime, timedelta

from django.http import HttpRequest
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

def home(request: HttpRequest):
    return render(request, "app_general/home.html")


def about(request: HttpRequest):
    return render(request, "app_general/about.html")


def change_theme(request: HttpRequest):
    referer = request.headers.get("referer")
    if referer is not None:
        response = HttpResponseRedirect(referer)
    else:
        response = HttpResponseRedirect(reverse("home"))

    # Theme
    theme = request.GET.get("theme")
    if theme == "dark":
        expired_date = datetime.now() + timedelta(days=365)
        response.set_cookie("theme", "dark", expires=expired_date, samesite="Lax")
    else:
        response.delete_cookie("theme")

    return response


def server_error(request):
    return render(request, 'app_general/500.html')

def page_not_found(request, exception):
    return render(request, 'app_general/404.html')

def permission_denied(request, exception):
    return render(request, 'app_general/403.html')

app_general/templates/app_general/components/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block site_title %}{% endblock %}Room Booking</title>
  <link rel="icon" href="{% static 'app_general/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'app_general/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'app_general/main.css' %}">
  <link rel="stylesheet" href="{% static 'app_general/main-dark.css' %}">
  <style>
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    main {
      flex: 1;
    }

    footer {
      flex-shrink: 0;
    }
  </style>
</head>

<body class="{{ request.COOKIES.theme }}">
  {% include 'app_general/components/site_header.html' %}
  <main>
    {% block content %}{% endblock %}
  </main>
  {% include 'app_general/components/site_footer.html' %}
  <script src="{% static 'app_general/main.js' %}"></script>
</body>

</html>

app_general/templates/app_general/components/site_footer.html
<footer class="site-footer">
  <!-- <h6></h6> -->
  <!-- <p>
    <a href="#">Facebook</a>
    <a href="#">Twitter</a>
    <a href="#">Instagram</a>
  </p> -->
  <p>
    <a href="{% url 'change_theme' %}?theme=default">Default theme</a>
    <a href="{% url 'change_theme' %}?theme=dark">Dark theme</a>
  </p>
  <p class="site-footer-copyright">Copyright 2024. All right reserved.</p>
</footer>

app_general/templates/app_general/components/site_header.html
{% load static %}
<header class="site-header">
  <div class="site-header-item">
    <a class="site-header-brand" href="{% url 'home' %}">
      <span>Room Booking System</span>
    </a>
  </div>
  <div class="site-header-menu">
    <div class="site-header-item">
      <a href="{% url 'app_booking:room_list' %}">
        <span>Rooms</span>
      </a>
    </div>
    {% if user.is_authenticated %}
    <div class="site-header-item">
      <a href="{% url 'app_booking:booking_list' %}">
        <span>Booking</span>
      </a>
    </div>
    <div class="site-header-item">
      <a href="{% url 'dashboard' %}">
        <span>{{ user.username|capfirst }}</span>
      </a>
    </div>
    {% if user.is_superuser %}
    <div class="site-header-item">
      <a href="{% url 'user_list' %}">
        <span>Dashboard</span>
      </a>
    </div>
    <div class="site-header-item">
      <a href="{% url 'app_booking:booking_dashboard' %}">
        <span>Approval</span>
      </a>
    </div>
    <div class="site-header-item">
      <a href="{% url 'app_booking:admin_room_list' %}">
        <span>Room Magement</span>
      </a>
    </div>
    
    {% endif %}
    <div class="site-header-item">
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">
          <span>Logout</span>
        </button>
      </form>
    </div>
    {% else %}
    <div class="site-header-item">
      <a href="{% url 'login' %}">
        <span>Login</span>
      </a>
    </div>
    <div class="site-header-item">
      <a href="{% url 'register' %}">
        <span>Register</span>
      </a>
    </div>
    {% endif %}
  </div>
  <div class="site-header-item">
    <a href="{% url 'about' %}">
      <span>About</span>
    </a>
  </div>
  <div class="site-header-item">
    <a class="site-header-toggle-menu-button">
      <span>MENU</span>
    </a>
  </div>
</header>